In [1]:
!pip install transformers datasets torch -q

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import re

from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer
import numpy as np
from sklearn.metrics import accuracy_score, f1_score

C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df = pd.read_csv("training.csv", encoding='latin-1', header=None)
df.columns = ["target", "id", "date", "flag", "user", "text"]
df["target"] = df["target"].replace(4, 1)

# 40k is enough
df = df.sample(15000, random_state=42)

df = df[["text", "target"]]
df.head()

                                                     text  target
541200             @chrishasboobs AHHH I HOPE YOUR OK!!!        0
750     @misstoriblack cool , i have no tweet apps  fo...       0
766711  @TiannaChaos i know  just family drama. its la...       0
285055  School email won't open  and I have geography ...       0
705995                             upper airways problem        0

In [4]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#", "", text)
    return text

df["text"] = df["text"].apply(clean_text)

In [5]:
dataset = Dataset.from_pandas(df)

# 👇 YE LINE ADD KAR (IMPORTANT)
dataset = dataset.rename_column("target", "labels")

dataset = dataset.train_test_split(test_size=0.2)

In [6]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize(example):
    return tokenizer(example["text"], truncation=True, padding="max_length", max_length=128)

dataset = dataset.map(tokenize, batched=True)

Map: 100%|██████████████████████████████████████████████████████████████| 12000/12000 [00:02<00:00, 5814.92 examples/s]
Map: 100%|████████████████████████████████████████████████████████████████| 3000/3000 [00:00<00:00, 6703.83 examples/s]

In [7]:
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|█████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 3124.30it/s]
DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [8]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1": f1_score(labels, preds)
    }

In [9]:
!pip install accelerate -q

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="no",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=1,
    logging_dir="./logs",
    logging_steps=100
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [11]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    compute_metrics=compute_metrics
)

In [12]:
trainer.train()

C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

KeyboardInterrupt:

In [ ]:
trainer.save_model("final_model")

In [ ]:
pred = trainer.predict(dataset["test"])

import numpy as np
from sklearn.metrics import accuracy_score

y_pred = np.argmax(pred.predictions, axis=1)
y_true = pred.label_ids

print("Final Accuracy:", accuracy_score(y_true, y_pred))

In [ ]:
def predict_sentiment(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    outputs = model(**inputs)
    pred = outputs.logits.argmax().item()
    
    return "Positive 😊" if pred == 1 else "Negative 😡"

# test
print(predict_sentiment("This product is amazing"))
print(predict_sentiment("Worst service ever"))